name: ovadm

services:
  puppet:
    build: docker
    container_name: ovadm-server
    hostname: puppet
    privileged: true
    ports:
      - "8140:8140"
    networks:
      - ovadm

  compiler01:
    build: docker
    container_name: ovadm-compiler01
    hostname: compiler01
    privileged: true
    networks:
      - ovadm

  agent:
    image: ghcr.io/openvoxproject/openvoxagent:latest
    container_name: ovadm-agent
    hostname: agent
    entrypoint: ["/bin/sleep"]
    command: ["infinity"]
    volumes:
      - ./docker/agent-puppet.conf:/etc/puppetlabs/puppet/puppet.conf:ro
    networks:
      - ovadm

networks:
  ovadm:
    driver: bridge
