targets:
  - name: puppet
    uri: docker://ovadm-server
    config:
      transport: docker

  - name: compiler01
    uri: docker://ovadm-compiler01
    config:
      transport: docker

  - name: agent
    uri: docker://ovadm-agent
    config:
      transport: docker
